-- What the food words were saying all along.
--
-- 112 of Google's words end in `restaurant` and all of them landed in one
-- drawer. The drawer is right — a place has one home — but italian, korean,
-- fine dining and family were being thrown away with it. Each word now carries
-- the secondary label it was always naming.
--
-- Only words that already point somewhere are touched: this adds a second thing
-- a word says, it never changes where a place lives. Words Google does not use
-- are inserted anyway and simply never match.
insert into taxonomy_label_carries (namespace, key, attribute_key, choice)
values
  ('google', 'african_restaurant', 'cuisine', 'African'),
  ('google', 'american_restaurant', 'cuisine', 'American'),
  ('google', 'argentinian_restaurant', 'cuisine', 'Argentinian'),
  ('google', 'asian_fusion_restaurant', 'cuisine', 'Fusion'),
  ('google', 'asian_restaurant', 'cuisine', 'Asian'),
  ('google', 'australian_restaurant', 'cuisine', 'Australian'),
  ('google', 'austrian_restaurant', 'cuisine', 'Austrian'),
  ('google', 'bangladeshi_restaurant', 'cuisine', 'Bangladeshi'),
  ('google', 'bar_and_grill', 'dining', 'Steakhouse'),
  ('google', 'barbecue_restaurant', 'cuisine', 'American'),
  ('google', 'basque_restaurant', 'cuisine', 'Basque'),
  ('google', 'bavarian_restaurant', 'cuisine', 'Bavarian'),
  ('google', 'beer_garden', 'cuisine', 'German'),
  ('google', 'belgian_restaurant', 'cuisine', 'Belgian'),
  ('google', 'bistro', 'dining', 'Bistro'),
  ('google', 'brazilian_restaurant', 'cuisine', 'Brazilian'),
  ('google', 'breakfast_restaurant', 'dining', 'Breakfast & brunch'),
  ('google', 'brewpub', 'cuisine', 'British'),
  ('google', 'british_restaurant', 'cuisine', 'British'),
  ('google', 'brunch_restaurant', 'dining', 'Breakfast & brunch'),
  ('google', 'buffet_restaurant', 'dining', 'Buffet'),
  ('google', 'burmese_restaurant', 'cuisine', 'Burmese'),
  ('google', 'burrito_restaurant', 'cuisine', 'Mexican'),
  ('google', 'cajun_restaurant', 'cuisine', 'Cajun'),
  ('google', 'californian_restaurant', 'cuisine', 'American'),
  ('google', 'cambodian_restaurant', 'cuisine', 'Cambodian'),
  ('google', 'cantonese_restaurant', 'cuisine', 'Cantonese'),
  ('google', 'caribbean_restaurant', 'cuisine', 'Caribbean'),
  ('google', 'chicken_wings_restaurant', 'cuisine', 'American'),
  ('google', 'chilean_restaurant', 'cuisine', 'Chilean'),
  ('google', 'chinese_noodle_restaurant', 'cuisine', 'Chinese'),
  ('google', 'chinese_restaurant', 'cuisine', 'Chinese'),
  ('google', 'coffee_stand', 'dining', 'Street food'),
  ('google', 'colombian_restaurant', 'cuisine', 'Colombian'),
  ('google', 'croatian_restaurant', 'cuisine', 'Croatian'),
  ('google', 'cuban_restaurant', 'cuisine', 'Cuban'),
  ('google', 'czech_restaurant', 'cuisine', 'Czech'),
  ('google', 'danish_restaurant', 'cuisine', 'Danish'),
  ('google', 'dim_sum_restaurant', 'cuisine', 'Chinese'),
  ('google', 'diner', 'dining', 'Diner'),
  ('google', 'dumpling_restaurant', 'cuisine', 'Chinese'),
  ('google', 'dutch_restaurant', 'cuisine', 'Dutch'),
  ('google', 'eastern_european_restaurant', 'cuisine', 'Eastern European'),
  ('google', 'ethiopian_restaurant', 'cuisine', 'Ethiopian'),
  ('google', 'european_restaurant', 'cuisine', 'European'),
  ('google', 'falafel_restaurant', 'cuisine', 'Middle Eastern'),
  ('google', 'family_restaurant', 'dining', 'Family'),
  ('google', 'filipino_restaurant', 'cuisine', 'Filipino'),
  ('google', 'fine_dining_restaurant', 'dining', 'Fine dining'),
  ('google', 'fish_and_chips_restaurant', 'cuisine', 'British'),
  ('google', 'fondue_restaurant', 'cuisine', 'Swiss'),
  ('google', 'food_court', 'dining', 'Street food'),
  ('google', 'food_delivery', 'dining', 'Takeaway'),
  ('google', 'french_restaurant', 'cuisine', 'French'),
  ('google', 'fusion_restaurant', 'cuisine', 'Fusion'),
  ('google', 'gastropub', 'dining', 'Gastropub'),
  ('google', 'german_restaurant', 'cuisine', 'German'),
  ('google', 'greek_restaurant', 'cuisine', 'Greek'),
  ('google', 'gyro_restaurant', 'cuisine', 'Greek'),
  ('google', 'halal_restaurant', 'cuisine', 'Middle Eastern'),
  ('google', 'hawaiian_restaurant', 'cuisine', 'Hawaiian'),
  ('google', 'hot_dog_restaurant', 'cuisine', 'American'),
  ('google', 'hot_dog_stand', 'dining', 'Street food'),
  ('google', 'hot_pot_restaurant', 'cuisine', 'Chinese'),
  ('google', 'hungarian_restaurant', 'cuisine', 'Hungarian'),
  ('google', 'indian_restaurant', 'cuisine', 'Indian'),
  ('google', 'indonesian_restaurant', 'cuisine', 'Indonesian'),
  ('google', 'irish_pub', 'cuisine', 'Irish'),
  ('google', 'irish_restaurant', 'cuisine', 'Irish'),
  ('google', 'israeli_restaurant', 'cuisine', 'Israeli'),
  ('google', 'italian_restaurant', 'cuisine', 'Italian'),
  ('google', 'japanese_curry_restaurant', 'cuisine', 'Japanese'),
  ('google', 'japanese_izakaya_restaurant', 'cuisine', 'Japanese'),
  ('google', 'japanese_restaurant', 'cuisine', 'Japanese'),
  ('google', 'kebab_shop', 'cuisine', 'Middle Eastern'),
  ('google', 'korean_barbecue_restaurant', 'cuisine', 'Korean'),
  ('google', 'korean_restaurant', 'cuisine', 'Korean'),
  ('google', 'latin_american_restaurant', 'cuisine', 'Latin American'),
  ('google', 'lebanese_restaurant', 'cuisine', 'Lebanese'),
  ('google', 'malaysian_restaurant', 'cuisine', 'Malaysian'),
  ('google', 'meal_delivery', 'dining', 'Takeaway'),
  ('google', 'meal_takeaway', 'dining', 'Takeaway'),
  ('google', 'mediterranean_restaurant', 'cuisine', 'Mediterranean'),
  ('google', 'mexican_restaurant', 'cuisine', 'Mexican'),
  ('google', 'middle_eastern_restaurant', 'cuisine', 'Middle Eastern'),
  ('google', 'mongolian_barbecue_restaurant', 'cuisine', 'Mongolian'),
  ('google', 'moroccan_restaurant', 'cuisine', 'Moroccan'),
  ('google', 'noodle_restaurant', 'cuisine', 'Asian'),
  ('google', 'noodle_shop', 'cuisine', 'Asian'),
  ('google', 'north_indian_restaurant', 'cuisine', 'Indian'),
  ('google', 'oyster_bar_restaurant', 'cuisine', 'Seafood'),
  ('google', 'pakistani_restaurant', 'cuisine', 'Pakistani'),
  ('google', 'persian_restaurant', 'cuisine', 'Persian'),
  ('google', 'peruvian_restaurant', 'cuisine', 'Peruvian'),
  ('google', 'pizza_delivery', 'dining', 'Takeaway'),
  ('google', 'pizza_restaurant', 'cuisine', 'Italian'),
  ('google', 'polish_restaurant', 'cuisine', 'Polish'),
  ('google', 'portuguese_restaurant', 'cuisine', 'Portuguese'),
  ('google', 'ramen_restaurant', 'cuisine', 'Japanese'),
  ('google', 'romanian_restaurant', 'cuisine', 'Romanian'),
  ('google', 'russian_restaurant', 'cuisine', 'Russian'),
  ('google', 'scandinavian_restaurant', 'cuisine', 'Scandinavian'),
  ('google', 'seafood_restaurant', 'cuisine', 'Seafood'),
  ('google', 'shawarma_restaurant', 'cuisine', 'Middle Eastern'),
  ('google', 'snack_bar', 'dining', 'Street food'),
  ('google', 'soul_food_restaurant', 'cuisine', 'American'),
  ('google', 'soup_restaurant', 'cuisine', 'Asian'),
  ('google', 'south_american_restaurant', 'cuisine', 'South American'),
  ('google', 'south_indian_restaurant', 'cuisine', 'Indian'),
  ('google', 'southwestern_us_restaurant', 'cuisine', 'American'),
  ('google', 'spanish_restaurant', 'cuisine', 'Spanish'),
  ('google', 'sri_lankan_restaurant', 'cuisine', 'Sri Lankan'),
  ('google', 'steak_house', 'cuisine', 'American'),
  ('google', 'steak_house', 'dining', 'Steakhouse'),
  ('google', 'sushi_restaurant', 'cuisine', 'Japanese'),
  ('google', 'swiss_restaurant', 'cuisine', 'Swiss'),
  ('google', 'taco_restaurant', 'cuisine', 'Mexican'),
  ('google', 'taiwanese_restaurant', 'cuisine', 'Taiwanese'),
  ('google', 'tapas_restaurant', 'cuisine', 'Spanish'),
  ('google', 'tex_mex_restaurant', 'cuisine', 'Mexican'),
  ('google', 'thai_restaurant', 'cuisine', 'Thai'),
  ('google', 'tibetan_restaurant', 'cuisine', 'Tibetan'),
  ('google', 'tonkatsu_restaurant', 'cuisine', 'Japanese'),
  ('google', 'turkish_restaurant', 'cuisine', 'Turkish'),
  ('google', 'ukrainian_restaurant', 'cuisine', 'Ukrainian'),
  ('google', 'vegan_restaurant', 'cuisine', 'Vegan'),
  ('google', 'vegetarian_restaurant', 'cuisine', 'Vegetarian'),
  ('google', 'vietnamese_restaurant', 'cuisine', 'Vietnamese'),
  ('google', 'western_restaurant', 'cuisine', 'American'),
  ('google', 'yakiniku_restaurant', 'cuisine', 'Japanese'),
  ('google', 'yakitori_restaurant', 'cuisine', 'Japanese')
on conflict (namespace, key, attribute_key) do nothing;
