/**
 * What every figure on these screens means, in the owner's own words.
 *
 * The law the design package states first: **no prose on any screen.** Not a
 * sentence of commentary, ever — if something needs explaining it goes in a
 * hover. So every column header, every stat label and **every data cell**
 * explains itself, and a cell inherits its column's explanation automatically
 * rather than being wired one at a time. A new column cannot ship with
 * unexplained figures under it, because the column definition carries the tip.
 *
 * Kept in one file rather than beside each table so that the same word means the
 * same thing in every lens — "one word, one meaning" is the sixth of the laws,
 * and two tables that had drifted apart would be impossible to notice.
 *
 * Copy is the design's, verbatim.
 *
 * **Nothing unused lives here.** Thirty-three of these were defined and
 * referenced by nothing (17 Sep 2026, the verification audit), in three
 * different ways: superseded by a hover the screen composes with the real
 * figures in it, duplicated from a source of truth on the API side — the fact
 * definitions in `domain/placeIndex.js`, the run definitions in
 * `repositories/runs.js`, the owed-item states in `HowItWorks.tsx` — or
 * unreachable because the figure the words explain is not on any board. All
 * three are the same mistake: a second place for the words to live, which is
 * exactly what this file exists to prevent. A tip whose figure is not drawn is
 * a missing figure, not a spare sentence.
 */

/** `[title, body]` — the title is the lime line above, the body the sentence under it. */
export type Tip = readonly [title: string, body: string];

export const TIPS = {

  // The section headings. The owner's own instruction (17 Sep 2026): "when I
  // hover over any 1 of the headers, it should give me a tooltip explaining
  // what the header is." The design tips its columns and its figures and leaves
  // its section headings bare; a section heading is a header.
  sectionCutBy: ['Cut by', 'Six ways of reading the same level: where the places are, what kind they are, who has seen them, how complete they are, what was asked for, and what we could go and get.'],
  sectionBreakDown: ['Break it down by', 'Which kind of area the rows are. A county in a country, a town or city under a county, or a postcode district — the same figures, cut three ways.'],
  sectionWhere: ['Where', 'Every town and postcode district that overlaps this area, with the six facts each needs. An outcode does not nest under a county — SL4 spans five councils — so both are listed together rather than one inside the other.'],
  sectionThisRing: ['This ring', 'What answering "within thirty minutes of here" actually cost. Every figure is measured rather than asserted: the rows read, the distances computed, and what went out to a provider.'],
  sectionLookingAt: ['Looking at', 'Six views of one place: what we hold, ours beside each provider\u2019s, how it scored, its pictures, what each source literally returned, and everything anybody has changed.'],
  sectionInputs: ['Inputs', 'Everything the score is worked out from, what each is worth towards it, and whether we may keep it. The figures add up to the score exactly.'],
  sectionWeights: ['Weights', 'The numbers the arithmetic uses, read out of the code rather than retyped here — so a change to the scoring cannot leave this table saying something else.'],
  sectionChangingTheShelf: ['Changing the shelf', 'A shelf is decided by a rule, not set on a place. How far a change would travel is said here before it travels; to change only this place, pin it.'],
  sectionOtherSystems: ['This place in other systems', 'Whose identifiers we hold for this place. An empty row is one of two different facts — we never asked, or we asked and there is no such place there — and the two are kept visibly apart.'],
  sectionNotChecked: ['Not checked', 'Sources that have never been asked about this place, what each would give us, and what each would cost. Nothing here has spent anything yet.'],
  sectionWhatWeCouldGet: ['What we could get here', 'Every source, what it has already given us, how many places it would be asked about, and what that would cost. The figures are the run\u2019s own, not an estimate.'],
  sectionDataScore: ['Data score', 'How the places here are spread across the score, worst band first. A tall bottom band is a county to collect in.'],
  sectionOldestFact: ['Oldest fact', 'How stale the facts are. A fact past its retention is one we may no longer compose from, so this is the ladder that decides what gets re-read.'],
  sectionWorthOwningNext: ['Worth owning next', 'The places here we hold nothing of our own about, most-visited first — so the next thing researched is the thing most people would notice.'],
  sectionShow: ['Show', 'Which places are listed: the ones that are not ready, the ones that are, or all of them.'],
  sectionSpend: ['Spend', 'What has gone out to providers this month against the ceiling you set. Nothing spends past it, and a run that would cross it is refused with what is left rather than half-done.'],
  sectionRunsThatSpend: ['Runs that spend', 'How many of the runs are going, what they have cost this month, and how many need somebody to look at them today.'],
  sectionToday: ['Today', 'What the runs have done since midnight.'],
  sectionFromHouseholds: ['From households', 'Everything a household made that somebody has to look at — photographs, reviews, ratings, notes, offers and messages — in one queue, because it is one act.'],
  sectionKind: ['Kind', 'Which sort of thing to look at. The counts follow the state chosen beside them.'],
  sectionState: ['State', 'Waiting, already approved, already rejected, or reported by somebody. Reported jumps the queue.'],
  sectionWhereItWouldGo: ['Where it would go', 'The place this would appear on, and what it would look like there, so the decision is made against what a household would see.'],
  sectionAboutIt: ['About it', 'Who made it, when, and what they have earned from what they have made before.'],
  sectionTheMessage: ['The message', 'Exactly what the household will receive, editable before it goes. A rejection stands whether or not a message goes out, and the screen says which.'],
  sectionOver: ['Over', 'How far back the figures reach. Demand cannot be backfilled, so a window longer than the log is a window with fewer searches in it, not an error.'],
  sectionRecentSearches: ['Searches · most recent first', 'Every search, as it happened: what was asked for, how many came back, and what the household did next. Open one to replay it exactly.'],
  sectionIfSaved: ['If saved', 'What changing this bar would do, before it does it: how many places would become ready, how many would stop being ready, and what Britain\u2019s figure would become.'],
  railBackOffice: ['Back office', 'Everything that is not the household app. The rail is grouped by what you would be here to do: run the business, work on the data, or set the place up.'],
  railReporting: ['Reporting', 'Six sections over one estate model: is the business growing, where the money comes from and what margin survives, what we sell and at what price, who the customers are, who we pay, and what households actually do. Two of them — Subscriptions and a supplier’s record — are where prices and rates get set, not only read.'],
  railData: ['Data', 'The screens about what Epic knows: where the places are, what was asked for, which providers gave us what, how things are filed, and the runs that fill the gaps.'],
  railAdmin: ['Admin', 'The screens that set the place up rather than use it — who may do what, what goes out by e-mail, and the decisions behind how it works.'],
  askedForName: ['Asked for', 'The second name this screen goes by. The design offers it as the alternative to "Demand" and the owner has not picked one, so both are on the board rather than one being chosen quietly.'],
  sectionLevel: ['What you are standing on', 'The kind of area, and — inside a ring — how far out and by what means. Everything below is about this and nothing else.'],
  sectionPicturesOnPlace: ['Pictures', 'The pictures we hold of this place and may keep. A rented one is shown greyed with its source said out loud; it is never stored.'],
  sectionPicturesHere: ['Pictures', 'Every picture matching the search, with what we are allowed to do with each.'],
  sectionSubcategoriesHere: ['Subcategories', 'Every drawer in the taxonomy, whether or not anything has landed in it — an empty one is the finding.'],
  sectionReadyWhen: ['Ready when it has', 'The facts this kind of place is judged on. Everything else is recorded when we have it and never counts against the score.'],
  sectionNextInQueue: ['Next', 'The next thing waiting, in full, so the queue keeps moving rather than sending you back to the list between every decision.'],
  sectionRejecting: ['Rejecting', 'Whose thing this is, the closed list of reasons, and the message they would receive — written next to the button that sends it.'],
  sectionRunFailures: ['This run', 'When it last ran and how much of it could not be done.'],
  sectionOurs: ['Ours', 'Failures that are our own bugs, on their own and above theirs. Folded in together they read as a hundred and thirty-two broken websites, which is how they sat in the backlog.'],
  sectionTheirs: ['Theirs', 'Failures that belong to the venue or their host — no website, a menu only on Facebook, a page that will not answer. Each one says what would fix it.'],
  sectionTheOneSelected: ['The one selected', 'Every licence field on this picture, and the page the attribution has to point at.'],
  afterTheChange: ['After the change', 'How many would meet the bar you are composing, as a share and a count.'],
  askedFor: ['Asked for', 'The subject a household searched for in the last 30 days.'],
  avgScore: ['Average score', 'The mean data score here, 0 to 100 — weighted completeness over the facts that kind of place needs. Not a place\'s Epic score, which ranks how good it is.'],
  avgScoreCategory: ['Average score', 'The mean data score of the places in this category here.'],
  avgScoreSubcategory: ['Average score', 'The mean data score of the places in this subcategory here.'],
  beenThere: ['Been there', 'How many people have left a review, added across every provider that has returned this place and banded at the moment of the call. A fact about how busy it is, not how good it is — and a word rather than a figure, because the figure is somebody else\'s and is never written down.'],
  britainOverall: ['Britain overall', 'The national readiness figure before and after the change.'],
  cap: ['Cap', 'The ceiling enforced before the call is made, not after.'],
  ceiling: ['Ceiling', 'The monthly spend limit. Nothing spends past it.'],
  checked: ['Checked', 'When we last confirmed it against its source.'],
  cityOrTown: ['City or town', 'Break the same level down by town instead of county. A town nests under its county; an outcode does not.'],
  collect: ['Collect', 'What we could get for this area, which sources could supply it and what each would cost. Starting a run happens here, where the gap is; the Runs page only watches what is already going.'],
  costs: ['Costs', 'What one run of this spends.'],
  countiesWhoseFigureMoves: ['Counties whose figure moves', 'How many counties would report a different readiness after this change.'],
  country: ['Country', 'Every place we have ever seen in that country, and whether its travel times are worked out yet.'],
  county: ['County', 'A county is a shape, so it needs no radius — a town or a postcode may take one.'],
  dataScore: ['Data score', 'Weighted completeness over the facts this kind of place needs, worked out again from scratch each time.'],
  dataScoreBand: ['Data score band', 'How many places here score in that range, out of 100.'],
  distancesComputed: ['Distances computed', 'How many point-to-point distances this ring had to work out. The reachable set is precomputed, so this is the cost of the answer rather than of the search.'],
  dwell: ['Dwell', 'How long they stayed on the place before leaving.'],
  editableColumn: ['Ours, so editable', 'We wrote or derived this, so it can be changed here. A provider\'s column cannot be edited — it changes when they change it.'],
  editableValue: ['Ours, so editable', 'Values we wrote or derived can be changed here. A provider\'s value cannot — it changes when they change it.'],
  empty: ['Came back empty', 'Of those searches, the ones we showed nothing for. A coverage hole, and Collect is where it gets fixed.'],
  emptyTotal: ['Came back empty', 'Searches we showed nothing for. A coverage hole.'],
  fact: ['Fact', 'One field a household would expect to see on the place.'],
  fault: ['Fault', 'Which of the three numbers on the left is the worst, named plainly. No places — we hold none, so nothing could be shown. Wrong places — we showed some and nobody opened them, so the mapping is off. Thin places — they were opened and nobody went, so the records are too sparse to convince. Under a fifth on all three reads Working; a fifth or more on all three reads All three.'],
  field: ['Field', 'Every field a place can carry, whether or not we hold it.'],
  fromHouseholds: ['From households', 'Photographs a household sent us. Ours to keep, unlike a provider\'s.'],
  google: ['Google', 'Rented: identifiers and counts only, with nothing stored.'],
  googleOnlyNoName: ['Google only, no name', 'Of those, the ones only Google has returned, so we hold no name for them. Fetching a name is a paid Google request; the board says what the run would cost before it runs.'],
  hours: ['Hours', 'Opening hours, and when they were last checked.'],
  howWeGotToHigh: ['How we got to this word', 'The rating every provider returned, pulled towards 4.15 in proportion to how few reviews there are, then banded: 4.55 and above is top, 4.3 to 4.54 high, 4.0 to 4.29 good, below that mixed. Only the word is kept — the rating and the counts are never written down.'],
  howWeGotToVeryBusy: ['How we got to this word', 'How many people have left a review, added across every provider that returned this place, banded at the moment of the call: two thousand and over is thousands, five hundred is many, a hundred is hundreds, below that a few. The figure itself is not stored.'],
  identifiedOnly: ['Identified only', 'We know from Google that the place exists and we own nothing about it. A place a household has saved is counted as Claimed rather than here.'],
  input: ['Input', 'One thing that went into the score.'],
  itsScore: ['Its score', 'That place\'s data score at the time they were shown it.'],
  known: ['Known', 'Every place any source has ever seen here, however little we hold about it.'],
  lastRun: ['Last run', 'When this last completed.'],
  menu: ['Menu', 'A menu we could read. Required for somewhere that serves food, never for a playground.'],
  missing: ['Missing', 'Of the three facts a playground needs — a picture, what it is, opening hours — how many we do not hold. Sortable.'],
  nearest: ['Nearest', 'How far the closest one is, as an estimate.'],
  nearestPostcodeArea: ['Nearest postcode area', 'A search from a map pin or a town name snaps to the nearest one.'],
  needsLookingAt: ['Needs looking at', 'Runs that stopped, failed or were never picked up.'],
  neverTripped: ['Never tripped', 'They opened a place and never added it to a trip, so the place itself was too thin to convince.'],
  noClick: ['Clicked nothing', 'They were shown places and opened none of them, so the wrong things were shown and the category rules need changing.'],
  noClickShort: ['Clicked nothing', 'They were shown places and opened none, so the wrong things were shown and the category rules need changing.'],
  noMatch: ['No match', 'We looked and this place is not in Wikidata.'],
  noRating: ['No rating', 'OSM carries no ratings, and no rating-bearing source has returned this place, so there is no band.'],
  matchedNotKept: ['Matched', 'We know which place this is at that source, and we keep nothing else from them. Their words, hours, photographs and ratings are rented and are read live when they are needed.'],
  sourcesFields: ['Fields', 'Which source can answer which fact, and what we are allowed to do with the answer. A tick is what the code actually asks for, not what the provider offers.'],
  sourcesWhatWeHold: ['What we hold', 'The facts in our own records right now, counted by where each one came from.'],
  sourcesProviders: ['Providers', 'Somebody else\u2019s data, keyed or open. Sample data is Epic\u2019s own and is not a provider.'],
  sourcesServices: ['Services', 'Things we run rather than data we fetch \u2014 a Claude read of a council page, a browser opening a menu. They cost money without being a source.'],
  sourcesCorrectness: ['Correctness', 'The bench: we ask a provider about places we already know, and count how often their answer agrees with ours. Their verdicts are kept, their values never are.'],
  sourcesRunsSoFar: ['Runs so far', 'Every correctness run to date, newest first, with what each one found.'],
  skillsPendingWords: ['Pending words', 'Words hosts have written that are not yet in the vocabulary. Approve one and it joins the list; merge it into an existing word and every host who typed it moves with it.'],
  accountsBand: ['Accounts', 'Every household with a sign-in, and what they together cost to serve this month.'],
  accountsHouseholds: ['Households', 'How many households have an account here. One household is one family, however many people are in it.'],
  accountsSignedIn: ['Signed in now', 'Households with at least one device signed in at this moment.'],
  accountsCallsMonth: ['Calls this month', 'Every outbound provider call made on behalf of anybody, this calendar month.'],
  accountsCostMonth: ['Cost this month', 'What those calls are estimated to have cost, at list price. Includes planning and speech as well as place data.'],
  accountsCostEver: ['Cost ever', 'The same figure since the ledger began.'],
  coverageBand: ['Coverage', 'How much of what we could know about our places we actually hold, measured place by place against the nine facts.'],
  howBand: ['How it works', 'A written account of every part of Epic and how the pieces fit, kept beside the code rather than in a folder somewhere.'],
  matchedHeldElsewhere: ['Matched · held elsewhere', 'We know which place this is at that source, and what it gave us is kept in its own place — the atlas keeps its descriptions and pictures with the attraction, not as fields on this record.'],
  standInName: ['Unnamed yet', 'The sweep found this place through Google, and a provider’s name is rented — so we hold where it is and what we searched for to find it, and not what it is called. It gets a name the day OpenStreetMap is matched to the same point, and that name is ours to keep.'],
  notAsked: ['Not asked', 'We have never spent a call asking this source about this place, so we hold no id for it there. Different from asking and finding nothing.'],
  notCounted: ['Not counted', 'A playground is not judged on this, so it never counts against the score. The bar is set per kind of place.'],
  nothingToCount: ['Nothing to count', 'No source that carries review counts has returned this place, so there is no figure — not a figure of zero.'],
  oldestFactBand: ['Oldest fact', 'How long ago the stalest fact on those places was last checked.'],
  oldestFactNever: ['Oldest fact', 'Places where nothing has ever been checked.'],
  oldestFactOver12: ['Oldest fact', 'These look complete and are not. Completeness on its own never shows this.'],
  oldestFactPlace: ['Oldest fact', 'How long ago the stalest fact on this place was checked.'],
  oneSourceOnly: ['One source only', 'Places here that a single source has ever returned. If that source went dark we would lose them.'],
  openTheRow: ['Open the row', 'Expands to the exact record and key it came from, and the raw value as the source returned it.'],
  opened: ['Opened', 'How many of them they tapped into.'],
  openingHours: ['Opening hours', 'When it is open, and how long ago we last checked.'],
  openstreetmap: ['OpenStreetMap', 'Ours to keep under its licence, which is why most of our names come from here.'],
  ourCategory: ['Our category', 'One of our 8. Every one is listed whether or not anything landed in it, because an empty one is the finding.'],
  ourScore: ['Our score', 'The composite we keep, worked out again from scratch every time rather than adjusted.'],
  ourSubcategory: ['Our subcategory', 'One of ours. Every one is listed whether or not anything landed in it, because an empty one is the finding.'],
  ours: ['Ours', 'Places here we hold our own research on.'],
  oursFault: ['Our own fault', 'Failures caused by our bugs rather than by the venue, kept separate so they cannot be skimmed past.'],
  oursFaultRow: ['Our own fault', 'How many failed this way. This one is a bug, not a venue problem.'],
  owned: ['Owned', 'We hold our own research on it, so it survives every provider going dark. A place a household merely saved is Claimed, not this.'],
  claimed: ['Claimed', 'A household saved, shortlisted or visited it, so it matters — but we still hold nothing of our own about it. The shortest list of places worth researching.'],
  ownedInput: ['Owned', 'Yes means we can keep this input for good — our own research, or a public register. No means it is licensed: we may read it to work out a band, but not store it, so it has to be fetched again.'],
  pictureFact: ['Picture', 'A photograph we own outright and may keep.'],
  pictures: ['Pictures', 'Photographs we own outright. Rented ones cannot be stored and do not count.'],
  placeRow: ['Place', 'Open it for every field, where each came from, and how it scored.'],
  placeWorth: ['Place', 'The place itself. Open it for every fact and where each came from.'],
  placesThatStopBeingReady: ['Places that stop being ready', 'How many fall below the new bar. The number going down is the point — it was wrong before.'],
  placesWithNoPicture: ['Places with no picture', 'Places where we hold no image we are allowed to keep.'],
  position: ['Position', 'Where it sat in the list they were shown. Anything they never reached is still logged.'],
  postcodeAreasInReach: ['Postcode areas in reach', 'How many areas fall inside the ring, read straight from what was worked out in advance.'],
  prices: ['Prices', 'Recorded when we have it. A playground is not judged on it, so it never counts against the score.'],
  providerSpend: ['Provider spend', 'What answering this cost in outbound calls.'],
  rating: ['Rating', 'A word, not a figure. At the moment of the call we read every provider\'s rating and how many people left it, pull the rating towards the average of everything the more thinly it is reviewed, and pick a band: 4.55 and above is top, 4.3 to 4.54 high, 4.0 to 4.29 good, below that mixed. The figures are then thrown away and only the word is kept, so a five from eleven diners cannot out-rank a 4.6 from two thousand.'],
  read: ['Read', 'Menus we successfully read.'],
  ready: ['Ready', 'Enough data to describe the place properly to a household. The bar is set per kind of place: a restaurant needs a menu, a playground never has one.'],
  readyShort: ['Ready', 'Enough data to describe the place properly to a household, with the bar set per kind of place.'],
  rented: ['Rented', 'It exists on Google but we cannot store it, so it does not count as a picture we own.'],
  reported: ['Reported', 'Content somebody has flagged. A different job on a different clock, so it jumps the queue.'],
  restaurantsReadyNow: ['Restaurants ready now', 'How many meet the current bar, as a share and a count.'],
  rowsRead: ['Rows read', 'How many database rows answered this ring. The reachable set is worked out in advance, so it is a read of the matrix rather than a search of the places.'],
  runTripadvisorCap: ['Tripadvisor', 'Opt-in and capped at 120 locations a month, enforced before the call is made.'],
  running: ['Running', 'Runs in flight now.'],
  saved: ['Saved', 'How many they kept.'],
  scoreNow: ['Score', 'This place\'s data score now, 0 to 100.'],
  scoreWeights: ['Score', 'Weighted completeness over the three facts a playground needs — a picture 30, what it is 25, opening hours 20. Equal completeness scores equally, and missing the picture costs most.'],
  searches: ['Searches', 'Searches for places in this area in the last 30 days.'],
  searchesRing: ['Searches', 'Searches from inside this ring in the last 30 days.'],
  seenBy: ['Seen by', 'How many providers have ever returned this place.'],
  shelf: ['Shelf', 'Which of our subcategories the place lands in.'],
  shown: ['Shown', 'How many places that household was given.'],
  source: ['Source', 'Where the value came from. Ours means we wrote or derived it, and those are the editable ones.'],
  sourceAtlas: ['The attraction harvest', 'Wikidata and Wikipedia, ours to keep.'],
  sourceSweep: ['The postcode sweep', 'Our own food census of an outcode.'],
  sourceTripadvisor: ['Tripadvisor', 'Opt-in and capped at 120 locations a month, so an empty column usually means we did not spend the call.'],
  spentThisMonth: ['Spent this month', 'What buying place data has cost. Every outbound call is attributed, so this is the real figure and not an estimate. Claude planning and speech are billed separately and are in Reporting.'],
  spentThisMonthCeiling: ['Spent this month', 'What buying place data has cost, against the ceiling nothing spends past. Every outbound call is attributed, so this is the real figure and not an estimate. Claude planning and speech are billed separately and are in Reporting.'],
  state: ['State', 'Where it has got to. There is no done state until something is done.'],
  subcategory: ['Subcategory', 'Which of our subcategories that place sits in.'],
  theRun: ['The run', 'One way of getting more data, with what it costs and what its cap is.'],
  theThreeFaultsAsABar: ['The three faults, as a bar', 'Left to right: came back empty, clicked nothing, never tripped. The widest band is where that subject is failing.'],
  thisIsTheRuleNotThisPlace: ['This is the rule, not this place', 'Changing it moves every place the rule catches. To change only Thorpe Park, pin it — a pin survives the next re-rank.'],
  travelTimes: ['Travel times', 'Whether we can answer "within 30 minutes" here. We work out the driving time between every postcode area once, so a search reads one row instead of doing sums.'],
  travelTimesWorkedOut: ['Travel times worked out', 'When we last worked out the driving times. Redone yearly, or when the roads change materially.'],
  tried: ['Tried', 'Menus we attempted to read.'],
  tripped: ['Tripped', 'Whether any of it ended up in a trip.'],
  unseenBy: ['Unseen by', 'Sources that have never returned this place. One is named; more than one shows the count — open the place for which.'],
  unseenByPlace: ['Unseen by', 'Sources that have never returned this place. Listed on the right with what each would cost.'],
  waiting: ['Waiting', 'Household-made content nobody has looked at yet.'],
  sourcesAsked: ['Sources asked', 'Which sources this search actually went to. A source not named here was not asked, which is a different thing from a source that answered with nothing.'],
  anyDegraded: ['Any degraded', 'Whether a source failed, timed out or came back short on this search. A degraded source is why an answer can be thin without anything being missing from the index.'],
  namesRefetched: ['Names re-fetched for this replay', 'A provider\u2019s name is rented, so it is never written down: replaying a search that held only identifiers fetches the names again, and this is how many and what it cost.'],
  heldAgainst: ['Held against', 'Whose search this was \u2014 a household, or an account. Said, never shown: the name is not printed on a list.'],
  stillAnIdentifier: ['Still an identifier', 'Places in this replay we hold no name for at all, and why. They were shown as an identifier or not shown.'],
  madeBy: ['Made by', 'Whose it is, and how much of theirs we have kept before. A decision about one photograph is a decision about a person.'],
  whenItWasMade: ['When it was made', 'For a photograph, when it was taken; for anything else, when it was written. How long it has been waiting is on the stat above.'],
  facesInIt: ['Faces', 'One of the reasons for turning a photograph down is that somebody is in it, so the screen says whether anything has looked. "Not looked for" is an answer.'],
  pictureSize: ['Size', 'How big the file is, in pixels. A photograph too small to fill a hero is not worth keeping even when there is nothing wrong with it.'],
  pictureLicence: ['Licence', 'What we are allowed to do with it. A household\u2019s own photograph is theirs, given to us to show; everything else carries the licence it came with.'],
  earnedSoFar: ['Earned so far', 'What this household has earned in credit for the things of theirs we have kept.'],
  tabTheRecord: ['The record', 'Every fact we hold about this place, where each one came from, when it was last looked at and whether it counts towards ready.'],
  tabOursBesideTheirs: ['Ours beside theirs', 'The same facts in three columns \u2014 ours, Google\u2019s and Tripadvisor\u2019s \u2014 so a disagreement is visible. Opening it is a paid call, and the button says what it costs.'],
  tabHowItScored: ['How it scored', 'The workings: every input, its weight, whether we hold it, and the two scores out \u2014 one with the licensed inputs and one without.'],
  tabPictures: ['Pictures', 'Every picture on this place with its licence, its credit and whether it is ours to keep or only rented.'],
  tabWhatEachSourceReturned: ['What each source returned', 'The records themselves, as each source gave them to us. Nothing here is written down; it is what the comparison above was made from.'],
  tabHistory: ['History', 'What changed on this place, when, and which run or person changed it.'],
  detailReference: ['Reference', 'The exact record this value came out of \u2014 the row, the page or the entry \u2014 so it can be checked without guessing.'],
  detailRawValue: ['Raw value', 'What the source actually gave us, before anything of ours was done to it.'],
  detailSetBy: ['Set by', 'Which run, or which person, put this value here.'],
  detailCountsTowardsReady: ['Counts towards ready', 'Whether this fact is one the ready bar for this kind of place is judged on. A fact nothing is judged on is not a gap.'],
  rawSource: ['Source', 'Which source the record below came from. Nothing here is written down \u2014 it is what the comparison was made from, held for a few hours and then gone.'],
  rawWhatItReturned: ['What it returned', 'How many fields this source gave us for this place. Open the row to read them with their licence and how long we may keep each one.'],
  rawTheirIdentifier: ['Their identifier', 'What this source calls the place. Holding it is what makes the next question a single call.'],
  rawLastAnswered: ['Last answered', 'When this source last told us anything about this place.'],
  historyWhen: ['When', 'When the change happened, newest first.'],
  historyWhatChanged: ['What changed', 'The change itself \u2014 a fact filled in, a band recalculated, a source asked.'],
  historyWho: ['Who or what did it', 'The person, or the run. A run is named rather than called "the system".'],
  historyCost: ['What it cost', 'What that change spent with a provider, in pence. A change made from the open sources or from our own arithmetic costs nothing.'],
  pictureWhereFrom: ['Where it came from', 'Which ladder rung found it \u2014 the venue\u2019s own logo, Wikimedia Commons, Geograph, street level, or a household.'],
  pictureOnThePlace: ['On the place', 'Which place it is attached to, and in what part \u2014 the hero, or one of the rest. A picture attached to nothing is a picture nobody will see.'],
  picturePhotographer: ['Photographer', 'Who took it. On a licence that requires attribution this is not optional, and a missing one is why a picture cannot be shown.'],
  pictureCreditAs: ['Credit as', 'The exact line the licence requires us to print beside it.'],
  pictureAttributionPage: ['Attribution page', 'The page the picture came from, which is where the licence says to link.'],
  pictureLicencePage: ['Licence page', 'The licence itself, in full. Kept so a claim about what we may do with a picture can be checked rather than remembered.'],
  pictureFetched: ['Fetched', 'When we took our own copy. What we hold is the copy, not a link to theirs.'],
  lensCensus: ['Census', 'What exists here, per drawer, counted from Google\u2019s free IDs Only tier and written down. Nothing on this board can spend money: every figure was recorded when the census ran, and the census costs nothing.'],
  censusFree: ['This board is free', 'Every number here was written down when the census ran, and a census asks Google only for identifiers \u2014 the tier that costs nothing. Reading this board, at any reach, bills nobody. The paid controls are in the other lenses and each says its price before you tap it.'],
  censusRented: ['Coordinates are rented for thirty days', 'Google\u2019s terms let a coordinate be held for thirty days and no longer, so a point that came from Google expires and the sector worked out from it goes with it \u2014 a sector derived from a Google coordinate is still location data from Google. Points from the open map, the atlas harvest and our own research never expire. \u201cHeld here\u201d and \u201cgo within 7 days\u201d are this board\u2019s outcodes. \u201cDropped\u201d cannot be: by the time the row is written the place has no area any more, so that figure is the whole estate. A place still shows on a phone after its coordinate goes \u2014 a live search carries its own point \u2014 but it leaves the reachability matrix until it is searched for again.'],
  censusFound: ['Found', 'How many places this question actually surfaced. This is the answer to \u201chow many are there\u201d, and it is the number to compare with the open map.'],
  censusFiled: ['Filed', 'How many of them live on this shelf. A place is filed once and found by every question that reaches it \u2014 a golf course in a wood is both \u2014 so the small figure beside it is the overlap with other drawers.'],
  censusCheck: ['The free cross-check', 'What the open map, and for food the hygiene register, say is here. Both are free and neither reaches a household: they are here to tell a drawer that is genuinely empty from a question of ours that is not reaching what is there. A dash means nobody has checked, which is not the same as none.'],
  censusFloor: ['This count is a floor', 'Google answers with its top sixty and stops. A slice that came back full was truncated, so at least one question here could not be answered whole even after the census split it down to the smallest tile it will go to. The real number is higher than this one \u2014 how much higher, nobody can say from here.'],
  censusNothing: ['Found nothing, and where', 'Every drawer the census asked about and got nothing back for, with the outcodes it was empty in. A drawer empty everywhere is usually a question of ours that is not reaching what is there; a drawer empty in three outcodes and full in the rest is usually the ground. The open-map and hygiene counts beside each row are what tell the two apart, and neither costs anything.'],
  censusScored: ['Scored', 'How many carry an Epic score \u2014 our own number, built from Google\u2019s rating and our own signals, and refreshed quarterly.'],
  censusCutOff: ['Cut off', 'Google answers with its top sixty and stops. A slice that came back full was truncated, so this drawer\u2019s count is a floor rather than a total. The census splits a cut-off slice into four and asks again; this is what was still cut off when it ran out of splits.'],
  lensCoverage: ['Coverage', 'The same places cut by where they are: how many we know of in each town and postcode district, and how much of each one is ready.'],
  lensCategory: ['Category', 'The same places cut by our own shelves, driven by the taxonomy rather than the data \u2014 so a subcategory with nothing in it is a row that says so.'],
  lensSource: ['Source', 'The same places cut by who told us about them, so a place only one source has returned is visible as a risk.'],
  lensQuality: ['Quality', 'The same places cut by how good the record is: the score, how old the oldest fact is, and what is worth owning next.'],
  lensDemand: ['Demand', 'The same places cut by what was actually searched for here \u2014 so a gap can be ranked by whether anybody asked.'],
  weHoldNoneOfThis: ['We hold none', 'Nobody has filled this one in on our side. A hole is a finding: it is what Curate, Collect or a household upload would answer.'],
  howMuchEachColumnFilled: ['How much each column filled', 'Of the facts on this board, how many each column actually had a value for. Ours against theirs, on the place in front of you.'],
  addACountry: ['Add a country', 'A country is a row in our own location data and its figures are stamped from the places inside it, so adding one is the owner\u2019s to do on the location screens rather than a button that guesses.'],
  weKnowOf: ['We know of', 'How many places we hold here for that subject, however little we hold about each.'],
  website: ['Website', 'The venue\'s own site, which is where we are allowed to read from.'],
  weight: ['Weight', 'What this input is worth when it applies.'],
  weightAssumption: ['Weight', 'What we assume before we know anything else about a place of that kind.'],
  weightAssumptionCounts: ['Weight', 'How much the starting assumption is allowed to move the score.'],
  weightSplit: ['Weight', 'How the three parts of the score are balanced against each other.'],
  whatIsInReach: ['What is in reach', 'Everything inside the ring, read from the matrix rather than calculated.'],
  whatItGaveUs: ['What it gave us', 'The word or figure this input contributed. Hover any value below for the arithmetic behind it.'],
  whatItIsFact: ['What it is', 'A sentence of our own saying what the place is.'],
  whatItNeeds: ['What it needs', 'The facts this kind of place must have before it counts as ready.'],
  whatTheyDid: ['What they did', 'Whether they scrolled past it, opened it, saved it or never reached it.'],
  whatTheyWereShown: ['What they were shown', 'The results that household saw, in the order they saw them.'],
  whatWasAskedFor: ['What was asked for', 'The subject a household searched for. No subject given means they just asked what was on.'],
  whatWeHold: ['What we hold', 'Our own value. A dash is a hole to fill; n/a means this kind of place is not judged on it.'],
  whatWeOwe: ['What we owe', 'An obligation this work creates. A thing we have not done is said plainly rather than left off.'],
  whereItGotTo: ['Where it got to', 'How far the run reached. A deploy kills a run in flight, and it has to be told to pick up.'],
  whereOursCameFrom: ['Where ours came from', 'Which source gave us our version, and when it was last checked.'],
  wherePlace: ['Where', 'The postcode area the place sits in.'],
  whereRow: ['Where', 'A town, or an outcode our places fall in. They are listed together because an outcode does not nest under a county.'],
  whichFault: ['Which fault', 'Shown nothing, clicked nothing, or never tripped — three different faults.'],
  whoFixesIt: ['Who fixes it', 'Each fault has one owner, which is why there is no single rate on this screen.'],
  whose: ['Whose', 'Who has to act on it.'],
  withoutTheLicensedBit: ['Without the licensed bit', 'The same score with the two rented inputs removed — what survives a provider going dark.'],
  worth: ['Worth', 'What each input contributed. The column adds to the score above it.'],
  ourLabel: ['Their word', 'A word a provider uses for a kind of place, in our vocabulary — `namespace:key`. Every one is listed whether or not anything here carries it, because a word we have written a rule for and nothing lands on is a finding too.'],
  pointsAt: ['Points at', 'Which of our own labels this provider\'s word means. It is what lets a rule written in our words read a place said in theirs.'],
  unscored: ['Not scored yet', 'Places in a subcategory nobody has set a bar for. They are not nought — there is nothing yet to judge them against.'],
  edgeMinutes: ['A few minutes generous', 'The matrix is read a few minutes past what was asked, so a place at the edge of its postcode area is offered rather than lost. The exact pass then fences it.'],
} as const satisfies Record<string, Tip>;

export type TipKey = keyof typeof TIPS;

/** A tip by key, or a pair written in place where a figure explains only itself. */
export const tipOf = (t: TipKey | Tip | null | undefined): Tip | null =>
  (t == null ? null : typeof t === 'string' ? (TIPS[t] ?? null) : t);
