/**
 * The legal pages are the owner's legal pack, sections 1–3 (owner, 2 Oct 2026),
 * with the company's details filled in and nothing of the drafting left showing
 * except the square-bracket placeholders he has still to fill.
 */
import test from 'node:test';
import assert from 'node:assert/strict';
import { COOKIES, PRIVACY, TERMS, LAST_UPDATED } from '../src/site/pages/legal/legalDocs.ts';
import { parseLegal } from '../src/site/pages/legal/legalParse.ts';

test('the company is named as it is registered, and the contact is support@', () => {
  assert.match(TERMS, /MAKE IT EPIC LIMITED, a company registered in England and Wales under number 17445225, registered office 124 City Road, London EC1V 2NX/);
  assert.match(PRIVACY, /MAKE IT EPIC LIMITED \("Epic"\) is the controller/);
  for (const doc of [TERMS, PRIVACY, COOKIES]) {
    assert.doesNotMatch(doc, /\bLtd\b|Capital Office|124-128|privacy@epic\.day|\[company number\]|\[date\]/);
  }
  assert.equal(LAST_UPDATED, '2 October 2026');
  assert.match(PRIVACY, /ICO registration number: C2049207\b/);
});

test('nothing marked for deletion before publishing is published', () => {
  assert.doesNotMatch(COOKIES, /Implementation note|delete before publishing/i);
});

test('the placeholders still to fill are exactly the ones reported to the owner', () => {
  const left = [...new Set((TERMS + PRIVACY + COOKIES).match(/\[[^\]]+\]/g))].sort();
  assert.deepEqual(left, ['[13]', '[2]', '[30]', '[3]', '[Settings > Privacy]', '[Settings > Subscription]', '[Stripe]', '[link]', '[one month]', '[provider]', '[table generated by the consent platform: name, provider, purpose, type, duration]']);
});

test('the Markdown the pack uses is all understood: headings, lists, tables', () => {
  const blocks = parseLegal(PRIVACY);
  assert.ok(blocks.some((b) => b.kind === 'h' && b.text === 'Who we are'));
  const table = blocks.find((b) => b.kind === 'table');
  assert.ok(table && table.kind === 'table' && table.head.length === 3 && table.rows.length >= 10, 'the what-we-collect table, header and rows');
  assert.ok(blocks.some((b) => b.kind === 'ul'), 'the who-we-share-with list');
  assert.ok(!blocks.some((b) => b.kind === 'p' && /^\|/.test(b.text)), 'no table row left as a paragraph');
});
